### ISSUE TITLE
enaml diff-job panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by jim80net** [enaml-ops/enaml#3]
```
○ → enaml diff-job consul-agent "https://bosh.io/d/github.com/cloudfoundry/cf-release?v=23"{4,5}
Could not find release in local cache. Downloading now.
2318316533/2318316533
Could not find release in local cache. Downloading now.
2361144604/2361144604
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x28 pc=0x1178ed]

goroutine 1 [running]:
archive/tar.(*Reader).Read(0x0, 0xc82008c200, 0x200, 0x200, 0x1370028, 0x0, 0x0)
    /usr/local/Cellar/go/1.5.2/libexec/src/archive/tar/reader.go:742 +0x2d
bytes.(*Buffer).ReadFrom(0xc8200a4d78, 0x4248260, 0x0, 0x0, 0x0, 0x0)
    /usr/local/Cellar/go/1.5.2/libexec/src/bytes/buffer.go:173 +0x23f
github.com/xchapter7x/enaml/diff.(*Diff).JobDiffBetweenReleases(0xc8200a4ed0, 0x7fff5fbff6d7, 0xc, 0x7fff5fbff6e4, 0x3a, 0x7fff5fbff71f, 0x3a, 0x0, 0x0, 0x0, ...)
    /Users/x7x/.go/src/github.com/xchapter7x/enaml/diff/jobdiff.go:46 +0x3fb
main.main.func3(0xc820092640)
    /Users/x7x/personal-go/xchapter7x/enaml/cmd/enaml/main.go:64 +0x249
github.com/codegangsta/cli.Command.Run(0x422a20, 0x8, 0x0, 0x0, 0xc82000fb10, 0x1, 0x1, 0x48e5a0, 0x31, 0x0, ...)
    /Users/x7x/.go/src/github.com/codegangsta/cli/command.go:179 +0x1397
github.com/codegangsta/cli.(*App).Run(0xc8200846e0, 0xc82000a190, 0x5, 0x5, 0x0, 0x0)
    /Users/x7x/.go/src/github.com/codegangsta/cli/app.go:196 +0x1386
main.main()
    /Users/x7x/personal-go/xchapter7x/enaml/cmd/enaml/main.go:81 +0x26c

goroutine 17 [syscall, 3 minutes, locked to thread]:
runtime.goexit()
    /usr/local/Cellar/go/1.5.2/libexec/src/runtime/asm_amd64.s:1721 +0x1

goroutine 53 [IO wait]:
net.runtime_pollWait(0x1375850, 0x72, 0xc82000e210)
    /usr/local/Cellar/go/1.5.2/libexec/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82021e300, 0x72, 0x0, 0x0)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82021e300, 0x0, 0x0)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82021e2a0, 0xc820640000, 0x8000, 0x8000, 0x0, 0x1370050, 0xc82000e210)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc820616020, 0xc820640000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc8203345a0, 0x1375a48, 0xc820616020, 0x5, 0x0, 0x0)
    /usr/local/Cellar/go/1.5.2/libexec/src/crypto/tls/conn.go:455 +0xcc
crypto/tls.(*Conn).readRecord(0xc820086580, 0x4bed17, 0x0, 0x0)
    /usr/local/Cellar/go/1.5.2/libexec/src/crypto/tls/conn.go:540 +0x2d1
crypto/tls.(*Conn).Read(0xc820086580, 0xc820625000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/Cellar/go/1.5.2/libexec/src/crypto/tls/conn.go:901 +0x167
net/http.noteEOFReader.Read(0x1740728, 0xc820086580, 0xc82061a108, 0xc820625000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc8203b1940, 0xc820625000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    <autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc820602c00)
    /usr/local/Cellar/go/1.5.2/libexec/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc820602c00, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/Cellar/go/1.5.2/libexec/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc82061a0b0)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/transport.go:685 +0xc78

goroutine 54 [select, 1 minutes]:
net/http.(*persistConn).writeLoop(0xc82061a0b0)
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
    /usr/local/Cellar/go/1.5.2/libexec/src/net/http/transport.go:686 +0xc9d
```

**Comment by xchapter7x** [comment]
the jobname `consul-agent` doesn't exist in the release. It should be `consul_agent`

I will add better error handline, and perhaps a joblist output to make the issue more clear in the future.
